### ISSUE TITLE
Как подключить аккумулятор к wemos d1 mini чтобы он заряжался от сети

### ISSUE THREAD

**Issue by tmmwithidimka** [KushlaVR/WemosRemote#3]

**Comment by KushlaVR** [comment]
Можна використати такий метод.
ВАЖЛИВО!! - плата захисту має бути обов'язково! (або акумулятор має мати вбудовану плату захисту)
Суть методу:
Акумулятор підключається до пінів GND і +5V USB Гнізда. При підключенні зарядки до Wemos починається заряд акумулятора.
Щоб під час заряду не тратити енергію на роботу WIFI - можна випаяти з плати діод і встановити на його контакти кнопку.

![sch1](https://user-images.githubusercontent.com/25207683/77168819-275f2280-6ac1-11ea-8378-dbe017696417.jpg)

**Comment by tmmwithidimka** [comment]
Получается если без кнопки то так?
![OfZFSTlUw4Q](https://user-images.githubusercontent.com/59134063/77171579-b96d2800-6acd-11ea-90e9-c669c32cdc91.jpg)

**Comment by KushlaVR** [comment]
Да. Верно.
Но если без кнопки, то можна и на пин +5V
