### ISSUE TITLE
Адаптация кода

### ISSUE THREAD

**Issue by Yurez87** [KushlaVR/WemosRemote#4]
Виталий, здравствуйте,
Я работаю над проектом действующей модели троллейбуса МТБ-82. За основу взял плату ESP8266 и Ваш исходный код из проекта "Запорожец". Но, у меня еще стоит задача управления сервоприводом дверей. В идеале - это кнопки "открыть" и "закрыть". Как раз удается уложиться в бесплатные 5 элементов RemoteXY. В принципе, отчасти у меня это получилось сделать через слайдер, используя часть кода и setup.bin из проекта Claas.

К сожалению, я не программист, поэтому только отчасти смог скорректировать Ваш исходный код под свои задачи в arduino. Проблема возникла в редактировании страницы настроек, файла setup.bin. 

Был бы очень признателен, если бы Вы подсказали мне, как создается setup.bin, и как добавить туда поля настроек новых элементов.

**Comment by KushlaVR** [comment]
Setup.bin - ето собраная копия поддиректории data, которя находится в папке проекта.
Для сборки и загрузки setup.bin необходимо установить дополнение для Arduoino IDE
тут есть пошаговая инструкция.
https://www.instructables.com/id/Using-ESP8266-SPIFFS/
Я думаю сначала потренируйтесь на примере из статьи, чтоб понять что к чему и не мешало куча лишнего из моих примеров.

После того как получится - можна приступать к редактированию нужних нам  файлов.
Например берем за основу проект ZAZ965A

## 1. Начинаем с файла SetupController.h
В нем находятся обявления всех переменних связаних с модулем настройки
Нас интересует строка №10
struct ConfigStruct {
...
}
Между скобками все поля которие настраиваются
Нам нужно дописать туда те параметри, которих нам недостает
Например нежно добавить два параметра: минимальное и максимальное положение сервопривода двери. Названия нужно вибрать логичние и состоящие из латинских букв
Напимер door_open, door_close
Добавляем в конец структури ConfigStruct (конец структури там где закривается фигурная скобка)

```javascript
struct ConfigStruct {
public:
	String ssid;
	String password;
	bool debug;

	int center;
	int max_left;
	int max_right;
	int stearing_linearity;

	int controller_type;
	int min_speed;
	int inertion;
	int potentiometer_linearity;

	int front_light_on;
	int high_light_on;
	int parking_light_on;
	int turn_light_on;
	int turn_light_limit;

	int wipers_speed1;
	int wipers_speed2;

	int stop_light_duration;

	int beep_freq;
	int beep_duration;
	int beep_interval;

	int battary;
	int battary_calibration;

	int drive_mode;

	int door_open;
	int door_close;
};
```

## 2. Добваляем параметри к функциям записи и зчитивания конфигурации SetupController.cpp
Процедура void SetupController::loadConfig() - отвечает за считивание конфига с памяти
Она работает следующим образом. Если файл конфигурации не найден - она его создает с дефолтними настройками. Потом считивает файл и заполняет нашу структуру значениями из файла
if (!SPIFFS.exists("/config.json"))  - проверка на наличие файла. (! - означает НЕТ).
Тоесть если файл файл не найден то код в скобках после оператора IF - создаст его
Нам нежно туда добватиь толькочто создание нами параметри
Не имеет значения где добавлять. Главное сделать ето между функциями
```javascript
cfg.beginObject();
cfg.AddValue("ssid", "ZAZ965A");
cfg.AddValue("password", "12345678");
cfg.AddValue("mode", "debug");
//здеь гдето добавлять...
cfg.AddValue("door_open", "20");
cfg.AddValue("door_close", "80");
cfg.endObject();
```
Дальше по тексту (уже за приделами IF ) нужно также добавить код считивания значений из файла в структуру
```javascript
this->cfg->wipers_speed1 = cfg.getInt("wipers_speed1");
this->cfg->wipers_speed2 = cfg.getInt("wipers_speed2");
//Гдето здесь можна
this->cfg->door_open= cfg.getInt("door_open");
this->cfg->door_close= cfg.getInt("door_close");
```
## 3. Добавить наши параметри в функцию записи конфигурации в файл
```javascript
void SetupController::printConfig(JsonString * out, bool battary)
{
	out->beginObject();
	out->AddValue("ssid", cfg->ssid);
	out->AddValue("password", cfg->password);
//Гдето здесь можна
        out->AddValue("door_open", cfg->door_open);
        out->AddValue("door_close", cfg->door_close);
}
```
## 4. Добавть параметри в функцию обработчика кнопки Save на страничке настроек
```javascript
void SetupController::Setup_Post()
{

	if (webServer.hasArg("ssid")) { setupController.cfg->ssid = webServer.arg("ssid"); }
	if (webServer.hasArg("password")) { setupController.cfg->password = 
                                                                               webServer.arg("password"); }

if (webServer.hasArg("door_open")) { setupController.cfg->door_open= 
                                                                               webServer.arg("door_open").toInt(); }
	if (webServer.hasArg("door_close")) { setupController.cfg->door_close= 
                                                                               webServer.arg("door_close").toInt(); }

}
```
## 5. Финишная прямая index.html
На последок - нужно добавить параметри на страничку интерфейса пользователя
Для етого откройте data/index.html и добавте туда поля с названиями как у наших параметров

Можна скопировать схожие по функционалу поля в нужное место и подправить названия, Например в поданом примере я скопировал поля из блока настройки сервопривода руля

```javascript
                     <h2>Door</h2>
                     <div class="form-group">
                        <label>Open</label>
                        <div class="input-group">
                            <input type="number" maxlength="5" name="door_open" class="form-control" 
                                        step="1" min="0" max="180" required="required" />
                            <div class="input-group-append">
                                <span class="input-group-text">0<sup>o</sup>..180<sup>o</sup></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Close</label>
                        <div class="input-group">
                            <input type="number" maxlength="5" name="door_close" class="form-control" 
                                      step="1" min="0" max="180" required="required" />
                            <div class="input-group-append">
                                <span class="input-group-text">0<sup>o</sup>..180<sup>o</sup></span>
                            </div>
                        </div>
                    </div>
```


Все можна прошивать прошивку
И после загружать setup.bin (в аруино студии ета функция будет иметь название ESP8266 Sketch Data Upload)

**Comment by Yurez87** [comment]
Виталий, все получилось! Большое спасибо за подробное объяснение. Единственное, что мне не удалось сделать, так это подвязать к сервоприводу не слайдер, а кнопки. Сейчас управление сервоприводом осуществляется слайдером, что не очень удобно. Подозреваю, что можно легко задать параметры положения сервопривода при нажатых кнопках., но как это сделать, пока не догадался.

**Comment by KushlaVR** [comment]
Можно заменить "слайдер" на  елемент "Переключатель". Он имеет два положения On и OFF. Напимер назовем его door_switch. И в коде обработать ето состояние
```javascript
void loop(){
//...
//гдето в коде loop'а
  if (RemoteXY.door_switch == 1){
    door_servo.write(config.door_open);
  } else {
    door_servo.write(config.door_close);
  }
//...
}
```
